=== MrMetalero/DAM_LenguajeMarcas/XML/XSD Schema/Actividad1/Ejercicio1/marcadores1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="marcadores">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pagina" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" maxOccurs="1" minOccurs="1" type="xs:string"></xs:element> <!-- Las por defecto hehe-->
                            <xs:element name="descripcion" type="xs:string"></xs:element>
                            <xs:element name="url" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
           
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MrMetalero/DAM_LenguajeMarcas/XML/XSD Schema/Actividad1/Ejercicio1/marcadores1.xml
<?xml version="1.0" encoding="UTF-8"?>
<marcadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="marcadores1.xsd">
    <pagina>
        <nombre>Abrirllave</nombre>
        <descripcion>Tutoriales de informática</descripcion>
        <url>www.blblblb.es</url>

    </pagina>

    <pagina>
        <nombre>Wikipedia</nombre>
        <descripcion>blehbleebhe</descripcion>
        <url>uwulandiattp.gigapágina.com</url>

    </pagina>
    <pagina>
        <nombre>W3C</nombre>
        <descripcion>la pagina de w3c</descripcion>
        <url>la url</url>

    </pagina>
</marcadores>
