<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contabilidad [
    <!ELEMENT contabilidad (apunte*)>
    <!ELEMENT apunte (fecha,cantidad,concepto)>
    <!ELEMENT ingreso ((ingreso | gasto)*)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT concepto (#PCDATA)>
    <!ATTLIST apunte tipo CDATA #REQUIRED>
]>
<contabilidad>
    <apunte tipo="ingreso">
        <fecha>24 de febrero de 2011</fecha>
        <cantidad>1800,00 €</cantidad>
        <concepto>Salario</concepto>
    </apunte>
    <apunte tipo="gasto">
        <fecha>28 de febrero de 2011</fecha>
        <cantidad>74,25 €</cantidad>
        <concepto>Recibo luz</concepto>
    </apunte>
</contabilidad>